language: ruby

rvm:
  - ruby-2.4.5
  - ruby-2.5.3

before_install:
  - gem install bundler

script:
  - bundle exec rubocop -c .rubocop.yml
  - bundle exec rake spec

notifications:
  email: false
  slack: sachin21dev:J8sIAeYdBknOGbFHtrphiobX
