language: ruby

rvm:
  - ruby-2.2.9
  - ruby-2.3.7
  - ruby-2.4.4

before_install:
  - gem install bundler

script: 'bundle exec rake spec'

notifications:
  email: false
  slack: sachin21dev:J8sIAeYdBknOGbFHtrphiobX
